### ISSUE TITLE
Paper release

### ISSUE THREAD

**Issue by hecktriebla** [akarasman/yolo-heatmaps#1]
Hi,

this LRP implementation for YOLO is great!
I would really like to use it for my master thesis.
Will you publish a paper regarding your work, so I can cite it properly?

**Comment by akarasman** [comment]
Hi Peter, I'm glad you find my implementation useful :) . I'm planning on
expanding this project in the future so look out for that.

Regarding the paper, I have written and submitted one for IST 2022 that is
currently under review. Notification of acceptance is planned for the 15th
of May and the full paper deadline is for the 30th. I'll update my repo
with all the appropriate information once it is approved.

**Comment by akarasman** [comment]
Update : Our paper has been out for some days now, I have just added the citation information to the readme.
