### ISSUE TITLE
Expected condition, x and y to be on the same device

### ISSUE THREAD

**Issue by molnarszilard** [akarasman/yolo-heatmaps#13]
Hi, I tried to run the example notebook, however, when I call the explain() function, it says that in file 'lrp/yolo.py' the three arguments for torch.where() function are not on the same device.

```RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cuda:0 and CPU respectively```

I think the problem is that on line 359:
```explanation = torch.where(outlier_mask, lrp_p, torch.tensor(0.0))```
the torch.tensor(0.0) should be put on the GPU.

This is how I managed to run the code:

```
if self.device == "cuda":
  explanation = torch.where(outlier_mask, lrp_p, torch.tensor(0.0).cuda())
else:
  explanation = torch.where(outlier_mask, lrp_p, torch.tensor(0.0))
```

A similar solution could be implemented in your code as well.

Regardless, thanks for sharing the code, it is helpful.

**Comment by akarasman** [comment]
Thank you very much for your observation. I never encountered this problem while testing. I have now updated the code with your suggestion to : 

```
explanation = torch.where(outlier_mask, lrp_p, torch.tensor(0.0, device=self.device))
```

(updated version will be uploaded soon)
