### ISSUE TITLE
How to implement this on customize dataset?

### ISSUE THREAD

**Issue by noreenanwar** [akarasman/yolo-heatmaps#3]
how to train this for customized dataset??

**Comment by noreenanwar** [comment]
How to implement this for customize dataset??

**Comment by akarasman** [comment]
Hi !

You can train a YOLOv5 model on whatever dataset you like by following the instructions provided here : https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data

As long as you follow these instructions and select an architecture that is supported, all you have to do is  run the explain.py module in the command line and provide your custom model weights via the --weights argument.

**Comment by noreenanwar** [comment]
> Hi !
> 
> You can train a YOLOv5 model on whatever dataset you like by following the instructions provided here : https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data
> 
> As long as you follow these instructions and select an architecture that is supported, all you have to do is run the explain.py module in the command line and provide your custom model weights via the --weights argument.

ok Thank you so much..
